on:
  schedule:
    - cron: '*  * * * *'
    - cron: '30 3 * * 0,6'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Saturday or Sunday
        if: github.event.schedule != '30 3 * * 0,6'
        run: echo "This job runs every day except Saturday and Sunday at 3:30 AM UTC."

      - name: Every time
        if: github.event.schedule == '* * * * *'
        run: echo "This job runs every minute."