name: Download Artifact


on:
    workflow_run:
        workflows: ["Upload Artifacts"]
        types:
            - completed

jobs:
    download-artifacts:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Download artifact
              uses: dawidd6/action-download-artifact@v6
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                run_id: ${{ github.event.workflow_run.id }}
                name: my-artifact

            - name: Display artifact content
              run: |
                echo "This is the content of the artifact uploaded"
                cat artifact.txt
