name: Download Artifact


on:
    workflow_run:
        workflows: ["Upload Artifacts"]
        types:
            - completed

jobs:
    download-artifacts:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Download artifact
              uses: actions/download-artifact@v3
              with: 
                name: my-artifact

            - name: Display artifact content
              run: |
                echo "This is the content of the artifact uploaded"
                cat artifact.txt
