name: Python Script Execution

on: [push]

jobs:
  check_prime:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-Python@v2
        with:
          python-version: '3.8'
        
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          vitualenv venv 
          source venv/bin/activate

      - name: Run Python Script
        run: python is_prime.py 29




