name: Python Script Execution

on: [push]

jobs:
  check_prime:
    run-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-Python@v2
        with:
          Python-version: '3.8'
        
        - name: Install dependencies 
          run: |
            python -m pip install --upgrade pip
            pip install vitualenv
            vitualenv venv 
            source venv/bin/active

        - name: Run Python scritp
          run: python is_prime.py 29




